import Title from "../../Components/Title/Title";

const Enrich = () => {
    return (
        <div className="max-w-5xl mx-auto bg-white px-5 my-5 py-5">
            <Title title="Enrich"></Title>
            <p className="mt-10 mb-5">“Enhancing Resources and Increasing Capacities of Poor Households towards Elimination of their Poverty &#40;ENRICH&#41;” is an integrated poverty alleviation approach designed by PKSF to increase household’s socio-economic status and welfare on a sustained basis. The overarching objective of ENRICH is to help the poor to establish their human dignity by extending necessary services and creating an enabling environment so that they can increase their income, protect themselves from income erosion, improve their human capabilities, raise their social standing, and expand their choices. To that end, ENRICH provides wide-ranging support services and facilities in the areas of health, education, and training; facilities to widen the choices and opportunities of the participants of the programme, and offers services for enterprise development and demand-driven financial support.</p>
            <p className="mb-5"><span className="font-semibold">ENRICH Education Programme:</span> The ENRICH Education Programme primarily seeks to address the problem of drop-out of children from primary level education. Under this programme, at least one afternoon education centre has been established in every village under working Union. All students up to Class 2 are helped in these teaching centres to prepare the next days’ tasks, given that often there are no facilities and educational support for the students at their homes. These education centres take special care of students who are generally slow learners and need the extra help and time to grasp material taught at school. So far 20 education centres have been established in the working Union and about 600 students enrolled.</p>
            <p className="mb-5"><span className="font-semibold">ENRICH Health and Nutrition Programme:</span> The ENRICH Health and Nutrition Programme is designed to provide comprehensive primary healthcare services for all households in the selected Unions. Each household of Unions is visited by health volunteers and health assistants at least once a month to collect health related information about all its members. The information and data collected are recorded in the household health cards. The health assistants arrange satellite clinics every week which are attended by MBBS doctors. Health camps &#40;vision, dental, heart, diabetes, medicine, etc&#41; are also organized from time to time, with specialist doctors attending. In these camps, patients with serious ailments are referred to different public as well as private hospitals and clinics where their treatment is arranged free of cost. ENRICH has also launched a de-worming campaign, giving away free medicine &#40;albendezole&#41; to 100% of its registered households for all members above 5 years of age. During 2014-15, ENRICH programme arranged free cataract surgery of about 103 persons with the support from PKSF, Sitesavers and Dhaka Progressive Lions Hospital.</p>
            <p className="mb-5"><span className="font-semibold">Special Financial Assistance Programme:</span> Three types of special credit services have been designed for the ENRICH households: Income Generating Activities Loan &#40;IGAL&#41;, Livelihood Improvement Loan &#40;LIL&#41;, and Asset Creation Loan &#40;ACL&#41;. Under IGAL, eligible household members can take loan for more than one activity to increase their income. As for the purchase of necessary equipment and taking other actions related to livelihood improvement. In this case, the ceiling for a household is BDT 10,000 in purchasing any kind of productive asset. The ACL ceiling for a household is BDT 30,000 and the interest rate payable is 8%.</p>
            <p className="mb-5"><span className="font-semibold">Community-Based Interventions:</span> Under community-based interventions, various problems faced by a community are identified, which may include: need for tube-wells and sanitary latrines at public places &#40;schools, colleges, mosques, temples, library, etc.&#41;, problems relating to access to clean drinking water, need for small bridges and culverts for public use, lack of community awareness or capacity for immediate response to natural disasters, and so on. The ENRICH does not address such problems in all cases by itself. It does whatever is within its means and sensitizes and canvasses the appropriate service providers for action concerning relevant cases and usually that works.</p>
        </div>
    );
};

export default Enrich;