import Title from "../../Components/Title/Title";

const IslamicMicroFinanceProgram = () => {
    return (
        <div className="max-w-5xl mx-auto bg-white px-5 my-5 py-5">
            <Title title="Islamic Micro Finance Program"></Title>
            <p className="mt-10 mb-5">The micro-finance programme (MFP) of DAM Foundation for Economic Development (DFED) has been contributing significantly in improving economic and social conditions of many poor families in Bangladesh though financing their economic activities and supporting establishing small and medium enterprises. Basically DFED’s micro-finance is based on conventional financing system by charging fixed rate service charges. Suggestion came from various corners for making provision of Shariah compliant financial services. Accordingly, DFED developed pilot scheme and scale up plan of Islamic micro-finance for implementation in 2012. DFED started implementation of Islamic Microfinance Programme as pilot basis at selected five branches in Narsingdi during 2013. From 2014, DFED started implementation of Islamic Microfinance Programme as a core component and expanded its area coverage.In 2019-20,DFED switched from conventional Microfinance Programmeto completely shariah based investment programme entitled <span className="font-semibold italic">“Shanti Investment Programme”</span>. From the beginning of the year 2019-20, Sariah based products and policy has been implemented across DFED instead of conventional microfinance programme.</p>
            <p className="mb-5"><span className="font-semibold">SHANTI Investment Programme: </span>DFED has been implementing Shariah based inclusive financing programme entitled “Shanti Investment Program” since July 2019. Shanti investment is similar to Bai-Muajjal. Bai-Muajjal may be defined as a contract between a Buyer and a Seller under which the Seller sells certain specific goods permissible under Islamic Shari‘ah to the Buyer at an agreed fixed price payable at a fixed future date in lump sum  or  within a fixed period by fixed instalments. The seller may also sell the goods purchased by him as per order and specification of the Buyer. ” Bai-Muajjal”  means sale for which payment is made at a future fixed date or within a fixed period. In short, it is a sale on Credit. Financial inclusion using Shariah based financing model has emerged as a powerful tool for promoting inclusive economic growth, eradicating poverty and reducing inequality.</p>
        </div>
    );
};

export default IslamicMicroFinanceProgram;